//! `open_enum!`: string enums that never fail to parse.
//!
//! Meta adds enum values to webhooks without notice (a new template status, a
//! new restriction type). A closed `#[derive(Deserialize)]` enum would turn
//! such a value into a parse failure for the whole change, so every enum in
//! this crate is generated by this macro instead: the values the docs list
//! become variants, anything else lands in `Other(String)` verbatim, and a
//! non-string JSON value (Meta's examples occasionally print a number where
//! the prose says string) is kept as its JSON text rather than rejected.
//!
//! Aliases (`Variant => "wire" | "alias"`) exist only where Meta's own pages
//! spell the same value two ways; the first spelling is what we serialize.

/// Generate an open string enum. See the [module docs](self).
macro_rules! open_enum {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $(
                $(#[$vmeta:meta])*
                $variant:ident => $wire:literal $(| $alias:literal)*
            ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        #[non_exhaustive]
        $vis enum $name {
            $(
                $(#[$vmeta])*
                $variant,
            )+
            /// A value the docs this crate was written against do not list,
            /// kept verbatim so a new Meta value never fails a delivery.
            /// Construct values with `From<&str>` so a listed value maps to
            /// its variant rather than to `Other`.
            Other(String),
        }

        impl $name {
            /// The value as Meta sends it.
            pub fn as_str(&self) -> &str {
                match self {
                    $( Self::$variant => $wire, )+
                    Self::Other(value) => value.as_str(),
                }
            }
        }

        impl From<&str> for $name {
            fn from(value: &str) -> Self {
                match value {
                    $( $wire $(| $alias)* => Self::$variant, )+
                    other => Self::Other(other.to_owned()),
                }
            }
        }

        impl From<String> for $name {
            fn from(value: String) -> Self {
                match Self::from(value.as_str()) {
                    Self::Other(_) => Self::Other(value),
                    known => known,
                }
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_str(self.as_str())
            }
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                Ok(match <serde_json::Value as serde::Deserialize>::deserialize(deserializer)? {
                    serde_json::Value::String(value) => Self::from(value),
                    other => Self::Other(other.to_string()),
                })
            }
        }
    };
}

pub(crate) use open_enum;

#[cfg(test)]
mod tests {
    open_enum! {
        /// Test enum.
        pub enum Sample {
            /// A.
            A => "a",
            /// B, spelled two ways.
            B => "b-b" | "b_b",
        }
    }

    #[test]
    fn known_aliases_and_unknown_values_all_parse() {
        let parse = |s: &str| serde_json::from_str::<Sample>(s).unwrap();
        assert_eq!(parse(r#""a""#), Sample::A);
        assert_eq!(parse(r#""b_b""#), Sample::B);
        assert_eq!(parse(r#""b-b""#), Sample::B);
        assert_eq!(parse(r#""zzz""#), Sample::Other("zzz".into()));
        assert_eq!(parse("42"), Sample::Other("42".into()));
        assert_eq!(serde_json::to_string(&Sample::B).unwrap(), r#""b-b""#);
        assert_eq!(Sample::from(String::from("a")), Sample::A);
        assert_eq!(Sample::Other("x".into()).to_string(), "x");
    }
}
