//! Enums shared by template definitions, template info and the
//! authentication module. Values are the ones listed in
//! `reference/whatsapp-business-account/message-template-api` (schemas
//! section) unless noted.

use super::macros::string_enum;

string_enum! {
    /// Template category (`WhatsAppBusinessHSMTag`). Decides pricing and
    /// which components are allowed; see `templates/template-categorization`.
    pub enum TemplateCategory {
        /// One-time passcodes only, with an OTP button.
        Authentication => "AUTHENTICATION",
        /// Promotions, announcements, anything mixed or unclear.
        Marketing => "MARKETING",
        /// Follow-ups to a user action or request (order updates, …).
        Utility => "UTILITY",
        /// Listed by the reference enum; not described anywhere else.
        FreeService => "FREE_SERVICE",
    }
}

string_enum! {
    /// Template status (`WhatsAppBusinessHSMStatus`). Only `Approved`
    /// templates can be sent (`templates/overview#template-status`).
    pub enum TemplateStatus {
        /// Passed review; can be sent.
        Approved => "APPROVED",
        /// Archived after 12 months of inactivity; deleted 28 days later
        /// unless unarchived (`templates/template-archival`).
        Archived => "ARCHIVED",
        /// Deleted.
        Deleted => "DELETED",
        /// Disabled after repeated negative feedback.
        Disabled => "DISABLED",
        /// An appeal was requested.
        InAppeal => "IN_APPEAL",
        /// Listed by the reference enum without a description.
        LimitExceeded => "LIMIT_EXCEEDED",
        /// Paused for low quality (`templates/template-pausing`).
        Paused => "PAUSED",
        /// Under review.
        Pending => "PENDING",
        /// Deleted while messages using it were still undelivered; delivery
        /// is attempted for 30 days (`templates/template-management`).
        PendingDeletion => "PENDING_DELETION",
        /// Rejected in review.
        Rejected => "REJECTED",
    }
}

string_enum! {
    /// `parameter_format`: how placeholders are written in component text
    /// (`templates/overview#parameter-formats`). Meta defaults to
    /// positional when it is omitted.
    pub enum ParameterFormat {
        /// `{{first_name}}`: lowercase letters and underscores.
        Named => "NAMED",
        /// `{{1}}`, `{{2}}`, … in order, starting at 1.
        Positional => "POSITIONAL",
    }
}

string_enum! {
    /// `sub_category` (`WhatsAppBusinessHSMTagSubCategory`).
    pub enum TemplateSubCategory {
        /// Booking status.
        BookingStatus => "BOOKING_STATUS",
        /// Call permission request.
        CallPermissionsRequest => "CALL_PERMISSIONS_REQUEST",
        /// Flight delay and gate change alert.
        FlightDelayAndGateChangeAlert => "FLIGHT_DELAY_AND_GATE_CHANGE_ALERT",
        /// Fraud alert.
        FraudAlert => "FRAUD_ALERT",
        /// Order details.
        OrderDetails => "ORDER_DETAILS",
        /// Order status.
        OrderStatus => "ORDER_STATUS",
        /// Rich order status.
        RichOrderStatus => "RICH_ORDER_STATUS",
        /// Seen in the list example of `templates/template-management`
        /// (`"sub_category": "CUSTOM"` on a marketing template) but not in
        /// the reference enum.
        Custom => "CUSTOM",
    }
}

string_enum! {
    /// `display_format` (`WhatsAppBusinessMessageDisplayFormat`).
    pub enum DisplayFormat {
        /// Order details display.
        OrderDetails => "ORDER_DETAILS",
    }
}

string_enum! {
    /// `send_type` for Marketing Messages API templates
    /// (`WhatsAppBusinessMarketingMessagesHSMSendType`).
    pub enum SendType {
        /// Campaign sends.
        Campaign => "campaign",
        /// Direct sends.
        Direct => "direct",
    }
}

string_enum! {
    /// `source` (`WhatsAppBusinessHSMSource`): how the template was created.
    /// Direct Send's auto-generated templates are listed with
    /// `source=AUTO_GENERATED` (`direct-send/view-generated-templates`).
    pub enum TemplateSource {
        /// Generated by Meta (Direct Send).
        AutoGenerated => "auto_generated",
        /// Created by the business.
        Manual => "manual",
    }
}

string_enum! {
    /// Template quality rating (`WhatsAppBusinessHSMQualityScore`), see
    /// `templates/template-quality`.
    pub enum QualityRating {
        /// High quality.
        Green => "GREEN",
        /// Medium quality; may be paused or disabled soon.
        Yellow => "YELLOW",
        /// Low quality; paused automatically (`templates/template-pausing`).
        Red => "RED",
        /// No feedback yet (every new template starts here). This is a
        /// documented value, not the catch-all.
        Unknown => "UNKNOWN",
    }
}

string_enum! {
    /// `rejected_reason` (`WhatsAppBusinessHSMRejectionReason`).
    pub enum RejectionReason {
        /// Abusive content.
        AbusiveContent => "ABUSIVE_CONTENT",
        /// Category not available.
        CategoryNotAvailable => "CATEGORY_NOT_AVAILABLE",
        /// Category does not match the content.
        IncorrectCategory => "INCORRECT_CATEGORY",
        /// Formatting problem (placeholders, …).
        InvalidFormat => "INVALID_FORMAT",
        /// Not rejected.
        None => "NONE",
        /// Promotional content.
        Promotional => "PROMOTIONAL",
        /// Scam.
        Scam => "SCAM",
        /// Tag/content mismatch.
        TagContentMismatch => "TAG_CONTENT_MISMATCH",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_any_case_and_keeps_unknown_values() {
        let c: TemplateCategory = serde_json::from_str("\"marketing\"").unwrap();
        assert_eq!(c, TemplateCategory::Marketing);
        assert_eq!(serde_json::to_string(&c).unwrap(), "\"MARKETING\"");
        let s: TemplateStatus = serde_json::from_str("\"FLAGGED_SOMEDAY\"").unwrap();
        assert_eq!(s, TemplateStatus::Other("FLAGGED_SOMEDAY".into()));
        assert_eq!(
            serde_json::to_string(&s).unwrap(),
            "\"FLAGGED_SOMEDAY\"",
            "unknown values round-trip"
        );
        let q: QualityRating = serde_json::from_str("\"UNKNOWN\"").unwrap();
        assert_eq!(q, QualityRating::Unknown, "documented UNKNOWN is not Other");
        assert_eq!(
            "AUTO_GENERATED".parse::<TemplateSource>().unwrap(),
            TemplateSource::AutoGenerated
        );
    }
}
